### ISSUE TITLE
How to use example (underline/ bold)?

### ISSUE THREAD

**Issue by tukao89** [sebmeister2077/editorjs-multiblock-selection-plugin#1]
I added underline/ bold extended but no toolbar open when selected multiple block.
Can you add an example? Thanks.

**Comment by sebmeister2077** [comment]
What version of editor do you use? Currently i only have it working for a few versions

**Comment by sebmeister2077** [comment]
@tukao89  Current examples are working only with verison 2.23 - 2.28

**Comment by sebmeister2077** [comment]
Update: all versions since 2.20 (to version 2.30.7) should work now :D if you still encounter issues let me know
